#!/usr/bin/env python3
"""Deterministic synthetic FASTQ + primer-config generator for the parity test.

The fixture must be public (it ships with the repo) but the original lab
primers / sequencing data are not. This script produces a fully synthetic
dataset whose primer sequences match no published or proprietary biology,
yet exercises every code path the byte-for-byte parity test cares about:

  - Two-round demultiplexing with a 1-bp barcode difference (ambiguity-vs-
    distinct paths)
  - Sense and antisense strand reads (RC retry path)
  - Reads with no anchor at all (no_anchor branch)
  - Low-quality reads (Q-filter / low_quality bucket)
  - In-frame CDS with no stop codons (passed_qc commit path)
  - Reads truncated past read-capacity (CDS truncation branch)

Re-running this script overwrites sample_1k.fastq + primers.yaml under the
same directory. The golden/ outputs must then be regenerated by:

    cd 01_scripts/
    python run_cli.py \\
        --config ../web/packages/core/test/fixtures/primers.yaml \\
        --fastqs ../web/packages/core/test/fixtures/sample_1k.fastq \\
        --output-dir ../web/packages/core/test/fixtures/golden/
"""

from __future__ import annotations

import os
import random
import yaml

# Seeded RNG so the fixture is bit-stable across machines / Python versions.
random.seed(42)

# Synthetic primers. Chosen so the last 10 bp (anchor) of R0_fw and R1_fw
# differ by exactly 1 base (position 10 from 3'-end) — this matches the
# original cDNA-display barcoding scheme without revealing the lab sequences.
# rv_primer is identical across rounds (typical for the technique).
ROUNDS: dict[str, dict[str, object]] = {
    "Round_0": {
        "fw_primer": "GTCAATGCCTAGAGGCTCAGATCG",  # anchor = GCTCAGATCG
        "rv_primer": "GCATCGATCGATCGATCGATTG",
        "cds_start": 1,
        "cds_end": 57,
    },
    "Round_1": {
        "fw_primer": "GTCAATGCCTAGAGGCTCAGATTG",  # anchor = GCTCAGATTG (1-bp diff)
        "rv_primer": "GCATCGATCGATCGATCGATTG",
        "cds_start": 1,
        "cds_end": 54,
    },
}

STOP_CODONS = {"TAA", "TAG", "TGA"}
BASES = ("A", "C", "G", "T")

READ_LENGTH = 150
N_READS = 1000


def random_dna(n: int) -> str:
    return "".join(random.choices(BASES, k=n))


def random_in_frame_dna(n_aa: int) -> str:
    """n_aa codons of random DNA, no stop codons."""
    out: list[str] = []
    for _ in range(n_aa):
        while True:
            codon = "".join(random.choices(BASES, k=3))
            if codon not in STOP_CODONS:
                out.append(codon)
                break
    return "".join(out)


def reverse_complement(seq: str) -> str:
    return seq.translate(str.maketrans("ACGT", "TGCA"))[::-1]


def build_sense_read(round_name: str) -> str:
    """A read containing the round's Fw primer + valid CDS + Rv RC anchor + pad."""
    cfg = ROUNDS[round_name]
    cds_len = int(cfg["cds_end"]) - int(cfg["cds_start"]) + 1  # type: ignore[arg-type]
    cds = random_in_frame_dna(cds_len // 3)
    rc_rv = reverse_complement(str(cfg["rv_primer"]))

    prefix = random_dna(random.randint(0, 3))
    middle = random_dna(random.randint(0, 5))
    core = prefix + str(cfg["fw_primer"]) + cds + middle + rc_rv

    if len(core) < READ_LENGTH:
        core += random_dna(READ_LENGTH - len(core))
    else:
        core = core[:READ_LENGTH]
    return core


def qual_high() -> str:
    return "I" * READ_LENGTH  # Phred 40, well above the threshold


def qual_low() -> str:
    return "$" * READ_LENGTH  # Phred 3, dropped by the Q-filter


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    fastq_path = os.path.join(here, "sample_1k.fastq")
    yaml_path = os.path.join(here, "primers.yaml")

    # Round distribution + noise mix:
    #   45% Round_0 sense (some antisense to exercise RC retry)
    #   45% Round_1 sense (some antisense)
    #   5%  no-anchor garbage
    #   5%  low-quality (passes pre-filter check only)
    with open(fastq_path, "w", encoding="utf-8", newline="\n") as f:
        for i in range(N_READS):
            r = random.random()
            if r < 0.05:
                seq = random_dna(READ_LENGTH)
                qual = qual_high()
            elif r < 0.10:
                seq = random_dna(READ_LENGTH)
                qual = qual_low()
            else:
                round_name = "Round_0" if r < 0.55 else "Round_1"
                seq = build_sense_read(round_name)
                if random.random() < 0.10:
                    seq = reverse_complement(seq)
                qual = qual_high()
            f.write(f"@synthetic_read_{i}\n{seq}\n+\n{qual}\n")

    with open(yaml_path, "w", encoding="utf-8", newline="\n") as f:
        yaml.safe_dump(
            {
                "rounds": ROUNDS,
                "settings": {"adaptive": True, "filter_stop": True},
            },
            f,
            sort_keys=False,
        )

    print(f"Wrote {fastq_path}")
    print(f"Wrote {yaml_path}")
    print(
        "Next: regenerate the golden outputs (see this file's docstring for "
        "the exact run_cli.py invocation)."
    )


if __name__ == "__main__":
    main()
