import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { AlertTriangle, ArrowLeft, BarChart3, ChevronDown, ChevronRight, Dna, Download, RefreshCw, Table2, TrendingUp } from "lucide-react";
import { TARGETED_NANOPORE_METHODS } from "@cdna/core";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { MethodsCard } from "@/components/MethodsCard";
import { LazyMount } from "@/components/LazyMount";
import { EnrichmentScatter } from "@/tools/cdna-display/viz/EnrichmentScatter";
import { TARGETED_EXPORT_FILES, exportTargetedOutcome, methodSettings, type TargetedExportSnapshot } from "@/adapters/TargetedNanoporeExporter";
import { useTargetedNanoporeStore } from "@/state/useTargetedNanoporeStore";
import type { TargetedNanoporeOutcome } from "@/worker/types";
import { TargetSiteSequenceLogo } from "../TargetSiteSequenceLogo";
import { TargetedFilterFunnelSankey } from "../TargetedFilterFunnelSankey";
import { targetedRowsToChartRows } from "../viz";

export function ResultsStep() {
  const s = useTargetedNanoporeStore();
  const o = s.runState.outcome;
  const [exporting, setExporting] = useState(false);
  const [qcOpen, setQcOpen] = useState(false);
  const last = o?.roundNames[o.roundNames.length - 1] ?? "";
  const chartRows = useMemo(() => o ? targetedRowsToChartRows(o.perSiteRowsForViz, o.roundNames).sort((a, b) => (b.centered[last] ?? -Infinity) - (a.centered[last] ?? -Infinity)) : [], [o, last]);
  const top20 = useMemo(() => o ? [...o.perSiteRowsForViz].filter((row) => Number.isFinite(Number(row[`Centered_Fitness_${last}`]))).sort((a, b) => Number(b[`Centered_Fitness_${last}`]) - Number(a[`Centered_Fitness_${last}`])).slice(0, 20) : [], [o, last]);
  if (!o) return <div className="space-y-4"><p>No completed run is available.</p><Button onClick={() => s.setStep("run")}>Go to Run</Button></div>;
  const total = o.roundNames.reduce((n, r) => n + o.statsByRound[r]!.total_reads, 0);
  const full = o.roundNames.reduce((n, r) => n + o.statsByRound[r]!.full_qc_passed, 0);
  const callable = o.roundNames.reduce((n, r) => n + o.siteNames.reduce((m, site) => m + o.statsByRound[r]!.sites[site]!.passed_qc, 0), 0);
  const snapshot: TargetedExportSnapshot = { projectName: s.projectName, referenceSeq: s.referenceSeq, cdsStart: s.cdsStart, cdsEnd: s.cdsEnd, cdsStrand: s.cdsStrand, sites: s.sites, settings: s.settings, reportHaplotypes: s.reportHaplotypes, startedAt: s.runState.startedAt, finishedAt: s.runState.finishedAt };
  const downloadAll = async () => { setExporting(true); try { await exportTargetedOutcome(o, snapshot); } finally { setExporting(false); } };

  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="grid grid-cols-1 gap-4 md:grid-cols-4"><Stat label="Total reads" value={total.toLocaleString()} /><Stat label="Full-read QC" value={full.toLocaleString()} tone="success" /><Stat label="Full-QC yield" value={pct(full, total)} tone="success" /><Stat label="Callable site observations" value={callable.toLocaleString()} /></div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary" />Filtering funnel</CardTitle><CardDescription>Sankey view of every read entering an exclusive whole-read outcome. Band width shows where throughput is being lost; site-level rescue remains separate.</CardDescription></CardHeader><CardContent><LazyMount minHeight={320}><TargetedFilterFunnelSankey outcome={o} /></LazyMount></CardContent></Card>

    {chartRows.length > 0 && <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-primary" />Enrichment scatter</CardTitle><CardDescription>RPM in the earlier versus later round on log scales. Each point is one site:amino-acid call; top 20 by enrichment are highlighted. This is descriptive and does not pool FDR families across sites.</CardDescription></CardHeader><CardContent><LazyMount minHeight={320}><EnrichmentScatter rows={chartRows} roundNames={o.roundNames} /></LazyMount></CardContent></Card>}

    {top20.length > 0 && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Table2 className="h-5 w-5 text-primary" />Top 20 by enrichment</CardTitle><CardDescription>Globally displayed by <code className="font-mono text-xs">Centered_Fitness_{last}</code>; FDR remains computed within each site family. Full matrix is downloadable.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2 pr-3">#</th><th className="pb-2 pr-3">Site</th><th className="pb-2 pr-3">AA</th><th className="pb-2 pr-3">DNA</th><th className="pb-2 pr-3 text-right">Count R0</th><th className="pb-2 pr-3 text-right">Count {last}</th><th className="pb-2 pr-3 text-right">Fitness</th><th className="pb-2 pr-3 text-right">Centered</th><th className="pb-2 text-right">FDR q</th></tr></thead><tbody>{top20.map((row, index) => <tr className="border-b last:border-0" key={`${row.Site}:${row.Variant_AA}`}><td className="py-1.5 pr-3 text-muted-foreground">{index + 1}</td><td className="py-1.5 pr-3 font-mono">{row.Site}</td><td className="py-1.5 pr-3 font-mono">{row.Variant_AA}</td><td className="py-1.5 pr-3 font-mono">{row.Dominant_DNA}</td><td className="py-1.5 pr-3 text-right font-mono">{num(row["Count_Round 0"])}</td><td className="py-1.5 pr-3 text-right font-mono">{num(row[`Count_${last}`])}</td><td className="py-1.5 pr-3 text-right font-mono">{fmt(row[`Fitness_vs_WT_${last}`])}</td><td className="py-1.5 pr-3 text-right font-mono text-primary">{fmt(row[`Centered_Fitness_${last}`])}</td><td className="py-1.5 text-right font-mono">{fmt(row[`FDR_q_${last}`])}</td></tr>)}</tbody></table></CardContent></Card>}

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Dna className="h-5 w-5 text-primary" />Sequence logo</CardTitle><CardDescription>Nanopore-targeted version of the NGS logo: each column is a confirmed target codon and letter heights are weighted by callable read counts in that round.</CardDescription></CardHeader><CardContent><LazyMount minHeight={280}><TargetSiteSequenceLogo rows={o.perSiteRowsForViz} roundNames={o.roundNames} siteNames={o.siteNames} /></LazyMount></CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary" />Per-round yield</CardTitle><CardDescription>Full-reference yield plus independent site rescue. Callable observations can exceed reads because one long read can cover several target codons.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-2 pr-4">Round</th><th className="pb-2 pr-4 text-right">Total</th><th className="pb-2 pr-4 text-right">Aligned</th><th className="pb-2 pr-4 text-right">Full QC</th><th className="pb-2 pr-4 text-right">Callable sites</th><th className="pb-2 pr-4 text-right">Rescued sites</th><th className="pb-2">Yield</th></tr></thead><tbody>{o.roundNames.map((round) => { const x = o.statsByRound[round]!; const calls = o.siteNames.reduce((n, site) => n + x.sites[site]!.passed_qc, 0); const rescued = o.siteNames.reduce((n, site) => n + x.sites[site]!.callable_rescued, 0); return <tr className="border-b last:border-0" key={round}><td className="py-2 pr-4 font-mono text-xs">{round}</td><td className="py-2 pr-4 text-right font-mono text-xs">{x.total_reads.toLocaleString()}</td><td className="py-2 pr-4 text-right font-mono text-xs">{x.aligned.toLocaleString()}</td><td className="py-2 pr-4 text-right font-mono text-xs text-success">{x.full_qc_passed.toLocaleString()}</td><td className="py-2 pr-4 text-right font-mono text-xs">{calls.toLocaleString()}</td><td className="py-2 pr-4 text-right font-mono text-xs">{rescued.toLocaleString()}</td><td className="w-40 py-2"><YieldBar pct={x.total_reads ? x.full_qc_passed / x.total_reads * 100 : 0} /></td></tr>; })}</tbody></table></CardContent></Card>

    <Card><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><CardTitle>Downloads</CardTitle><CardDescription>Same three-artifact structure as NGS; detailed Nanopore data are nested in run_stats.json instead of split across many files.</CardDescription></div><Button onClick={() => void downloadAll()} disabled={exporting}><Download className="mr-1.5 h-4 w-4" />{exporting ? "Preparing…" : "Download all"}</Button></CardHeader><CardContent><ul className="space-y-1 text-sm text-muted-foreground">{TARGETED_EXPORT_FILES.map(([name, description]) => <li key={name}>• <code className="font-mono text-xs">{name}</code> — {description}</li>)}</ul><p className="mt-3 text-xs text-muted-foreground">Exact codon counts, target haplotypes, haplotype statistics, file QC, funnel and site callability are retained inside <code>run_stats.json</code>.</p></CardContent></Card>

    <div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-xs text-amber-950 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><AlertTriangle className="mr-2 inline h-4 w-4" /><strong>Low-throughput interpretation:</strong> without biological replicates, Z/p/FDR represent Poisson counting uncertainty and usually underestimate total experimental uncertainty. Use the plots for prioritization and inspect WT depth and variance before biological claims.</div>

    <Card><button type="button" className="w-full text-left hover:bg-muted/40" onClick={() => setQcOpen((open) => !open)}><CardHeader><CardTitle className="flex items-center gap-2 text-base">{qcOpen ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}QC logic, abnormal events &amp; audit tables</CardTitle><CardDescription className="ml-6">Detailed substitution/indel/rescue behavior and counters for users auditing the pipeline.</CardDescription></CardHeader></button>{qcOpen && <CardContent className="space-y-5"><div className="grid gap-3 text-sm md:grid-cols-2"><Logic title="Substitution outside targets">Retained while target-masked protected identity passes. Accumulated fixed-region mismatches may indicate a wrong reference or poor base-calling.</Logic><Logic title="Substitution inside a target">Called only when all three bases are projected, unambiguous and ≥ target Q. Intended NNK changes do not penalize protected identity.</Logic><Logic title="Insertion / deletion at a target">Only the overlapping site becomes non-callable and enters target_indel; valid distant sites remain usable.</Logic><Logic title="Insertion / deletion in protected sequence">Small CIGAR-projected events are tolerated up to 30 nt. Larger protected disruption fails the whole read.</Logic><Logic title="Partial read rescue">Requires passing 30-nt flanks on both sides. It contributes to independent site counts but never to a multi-site haplotype.</Logic><Logic title="Off-NNK and stop calls">Retained as synthesis/base-calling diagnostics and never silently converted to WT.</Logic></div><QcFunnel outcome={o} /><SiteTable outcome={o} /></CardContent>}</Card>

    <MethodsCard doc={TARGETED_NANOPORE_METHODS} settings={methodSettings(snapshot)} libraryMedian={o.libraryMedianFitness} hitCounts={o.hitCounts} />

    <div className="flex flex-wrap justify-between gap-2"><Button variant="outline" onClick={() => s.setStep("run")}><ArrowLeft className="mr-2 h-4 w-4" />Back to run</Button><Button onClick={s.prepareNextRun}><RefreshCw className="mr-2 h-4 w-4" />Next run</Button></div><p className="text-center text-xs text-muted-foreground">Next run preserves reference, CDS, target sites and QC values, but clears the previous FASTQs and results.</p>
  </div>;
}

function QcFunnel({ outcome: o }: { outcome: TargetedNanoporeOutcome }) { return <div><h4 className="mb-2 text-sm font-medium">Exclusive whole-read funnel</h4><div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead><tr><th className="text-left">Round</th><th>Malformed</th><th>Duplicate</th><th>Low Q</th><th>Concatemer</th><th>Align fail</th><th>Partial</th><th>Low align ID</th><th>Low protected ID</th><th>Protected indel</th></tr></thead><tbody>{o.roundNames.map((round) => { const d = o.statsByRound[round]!.primary_drop_reasons; return <tr className="border-t" key={round}><td className="text-left">{round}</td><td>{d.malformed_fastq}</td><td>{d.duplicate_read_id}</td><td>{d.low_read_q}</td><td>{d.concatemer_or_chimera}</td><td>{d.alignment_failed}</td><td>{d.partial_reference}</td><td>{d.low_alignment_identity}</td><td>{d.low_protected_identity}</td><td>{d.protected_indel}</td></tr>; })}</tbody></table></div></div>; }
function SiteTable({ outcome: o }: { outcome: TargetedNanoporeOutcome }) { return <div><h4 className="mb-2 text-sm font-medium">Site callability</h4><div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead><tr><th className="text-left">Round / site</th><th>Callable</th><th>Full</th><th>Rescued</th><th>WT</th><th>Target indel</th><th>Low base Q</th><th>Not covered</th><th>Off-NNK</th><th>Stop</th></tr></thead><tbody>{o.roundNames.flatMap((round) => o.siteNames.map((site) => { const x = o.statsByRound[round]!.sites[site]!; return <tr className="border-t" key={`${round}:${site}`}><td className="text-left">{round} / {site}</td><td>{x.passed_qc}</td><td>{x.callable_full}</td><td>{x.callable_rescued}</td><td>{x.wt_count}</td><td>{x.target_indel}</td><td>{x.low_quality}</td><td>{x.not_covered}</td><td>{x.off_design}</td><td>{x.stop_codon}</td></tr>; }))}</tbody></table></div></div>; }
function Stat({ label, value, tone }: { label: string; value: string; tone?: "success" }) { return <Card><CardContent className="pt-6"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className={`mt-1 text-2xl font-semibold tabular-nums ${tone ? "text-success" : ""}`}>{value}</p></CardContent></Card>; }
function YieldBar({ pct: value }: { pct: number }) { return <div className="flex items-center gap-2"><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-success" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div><span className="w-14 text-right font-mono text-xs">{value.toFixed(1)}%</span></div>; }
function Logic({ title, children }: { title: string; children: ReactNode }) { return <div className="rounded-md border p-3"><div className="mb-1 font-medium">{title}</div><p className="text-xs text-muted-foreground">{children}</p></div>; }
function pct(value: number, denominator: number): string { return `${(denominator ? value / denominator * 100 : 0).toFixed(2)}%`; }
function fmt(value: unknown): string { if (value == null || value === "") return "—"; const n = Number(value); return Number.isFinite(n) ? n.toFixed(3) : "—"; }
function num(value: unknown): string { const n = Number(value); return Number.isFinite(n) ? n.toLocaleString() : "—"; }
