import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useTargetedNanoporeStore } from "@/state/useTargetedNanoporeStore";

function download(blob: Blob | null, name: string) {
  if (!blob) return;
  const url = URL.createObjectURL(blob), a = document.createElement("a");
  a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function ResultsStep() {
  const s = useTargetedNanoporeStore();
  const o = s.runState.outcome;
  if (!o) return <div className="space-y-4"><p>No completed run is available.</p><Button onClick={() => s.setStep("run")}>Go to Run</Button></div>;
  const last = o.roundNames[o.roundNames.length - 1];
  return <div className="space-y-6"><Card><CardHeader><CardTitle>Nanopore QC funnel</CardTitle><CardDescription>Exclusive whole-read drops and independent site-level rescue are reported separately.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-right text-xs"><thead><tr><th className="text-left">Round</th><th>Total</th><th>Duplicate</th><th>Concatemer</th><th>Aligned</th><th>Full QC</th><th>Alignment fail</th><th>Partial</th><th>Low protected identity</th><th>Protected indel</th></tr></thead><tbody>{o.roundNames.map((round) => { const x = o.statsByRound[round]!; return <tr className="border-t" key={round}><td className="text-left font-medium">{round}</td><td>{x.total_reads.toLocaleString()}</td><td>{x.duplicate_read_ids.toLocaleString()}</td><td>{x.primary_drop_reasons.concatemer_or_chimera.toLocaleString()}</td><td>{x.aligned.toLocaleString()}</td><td>{x.full_qc_passed.toLocaleString()}</td><td>{x.primary_drop_reasons.alignment_failed.toLocaleString()}</td><td>{x.primary_drop_reasons.partial_reference.toLocaleString()}</td><td>{x.primary_drop_reasons.low_protected_identity.toLocaleString()}</td><td>{x.primary_drop_reasons.protected_indel.toLocaleString()}</td></tr>; })}</tbody></table></CardContent></Card>
    <Card><CardHeader><CardTitle>Site callability</CardTitle><CardDescription>Full and rescued calls form each site denominator; only full calls form haplotypes.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-right text-xs"><thead><tr><th className="text-left">Round / site</th><th>Callable</th><th>Full</th><th>Rescued</th><th>WT</th><th>Target indel</th><th>Low base Q</th><th>Stop</th></tr></thead><tbody>{o.roundNames.flatMap((round) => o.siteNames.map((site) => { const x = o.statsByRound[round]!.sites[site]!; return <tr className="border-t" key={`${round}:${site}`}><td className="text-left">{round} / {site}</td><td>{x.passed_qc.toLocaleString()}</td><td>{x.callable_full.toLocaleString()}</td><td>{x.callable_rescued.toLocaleString()}</td><td>{x.wt_count.toLocaleString()}</td><td>{x.target_indel.toLocaleString()}</td><td>{x.low_quality.toLocaleString()}</td><td>{x.stop_codon.toLocaleString()}</td></tr>; }))}</tbody></table></CardContent></Card>
    <Card><CardHeader><CardTitle>Enrichment preview</CardTitle><CardDescription>Fitness is WT-normalized against Round 0. Inferential fields are blank when the Round 0 count is below the locked threshold.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-right text-xs"><thead><tr><th className="text-left">Site</th><th className="text-left">AA</th><th className="text-left">DNA</th><th>Count R0</th><th>Count {last}</th><th>Fitness</th><th>Centered</th><th>FDR q</th></tr></thead><tbody>{o.perSiteRowsPreview.slice(0, 100).map((row, i) => <tr className="border-t" key={i}><td className="text-left">{row.Site}</td><td className="text-left">{row.Variant_AA}</td><td className="text-left font-mono">{row.Dominant_DNA}</td><td>{Number(row["Count_Round 0"] ?? 0).toLocaleString()}</td><td>{Number(row[`Count_${last}`] ?? 0).toLocaleString()}</td><td>{fmt(row[`Fitness_vs_WT_${last}`])}</td><td>{fmt(row[`Centered_Fitness_${last}`])}</td><td>{fmt(row[`FDR_q_${last}`])}</td></tr>)}</tbody></table></CardContent></Card>
    <div className="flex flex-wrap gap-2"><Button onClick={() => download(o.perSiteCsvBlob, `${s.projectName}_enrichment_per_site.csv`)}>Download per-site CSV</Button>{o.haplotypeCsvBlob && <Button variant="outline" onClick={() => download(o.haplotypeCsvBlob, `${s.projectName}_haplotypes.csv`)}>Download haplotypes</Button>}<Button variant="outline" onClick={() => download(new Blob([JSON.stringify({ project: s.projectName, rounds: o.roundNames, settings: s.settings, sites: s.sites, statsByRound: o.statsByRound, fileStats: o.fileStats, libraryMedianFitness: o.libraryMedianFitness }, null, 2)], { type: "application/json" }), `${s.projectName}_nanopore_qc.json`)}>Download QC JSON</Button><Button variant="ghost" onClick={() => s.setStep("inputs")}>Review inputs</Button></div>
    <p className="text-xs text-muted-foreground">Statistical warning: without biological replicates, Z/p/FDR reflect count uncertainty under the Poisson approximation and generally underestimate total experimental uncertainty.</p>
  </div>;
}
function fmt(value: unknown): string { const n = Number(value); return Number.isFinite(n) ? n.toFixed(4) : "—"; }
